import { Lead } from './types';

export const INITIAL_LEADS: Lead[] = [
  {
    id: '1',
    companyName: 'CPA Pavement Services',
    category: 'Logistics / Paving',
    location: 'Harrisburg, PA',
    description: 'Heavy residential/commercial paving operations covering 7+ townships.',
    phone: '(717) 564-5630',
    email: 'info@cpa-pave.com',
    painPoint: 'Dispatching multiple crews across wide areas and bottlenecked manual quoting.',
    pitchTitle: 'Automated Quoting & Dispatch',
    pitchText: 'I know from my own logistics background how chaotic it gets managing paving crews across Lower-Paxton and Camp Hill. I can build you an automated lead-to-quote SMS system and a clean dispatch dashboard to cut your admin time in half.',
    status: 'New Lead',
    colorHint: 'orange',
    yearsOperational: '15+ Years',
    currentStandings: '4.6/5 Stars (Google)',
    businessReview: 'Solid regional player with a strong fleet, but heavily reliant on legacy dispatch methods and whiteboards.'
  },
  {
    id: '2',
    companyName: 'Neffsville Plumbing & HVAC',
    category: 'HVAC / Emergency',
    location: 'Hummelstown, PA',
    description: 'Heavy emphasis on "Same-Day Service" and emergency dispatching.',
    phone: '(717) 625-1000',
    email: 'Via Website Form',
    painPoint: 'Managing the chaos of incoming emergency calls while tracking field tech locations and NATE-certifications.',
    pitchTitle: 'AI Triage & Auto-Dispatch',
    pitchText: 'When emergencies hit, dispatching becomes a nightmare. I can build an AI SMS bot that answers emergency texts, categorizes the plumbing/HVAC issue, and automatically pings the nearest available NATE-certified tech, saving your dispatchers hours.',
    status: 'Contacted',
    colorHint: 'blue',
    yearsOperational: 'Est. 1998',
    currentStandings: 'Top Rated Locally',
    businessReview: 'High volume of emergency calls. Excellent customer service reputation but likely bleeding margin on inefficient routing.'
  },
  {
    id: '3',
    companyName: 'Statewide Property Mgmt',
    category: 'Property Management',
    location: 'Harrisburg, PA',
    description: 'Managing multi-family units and HOAs. High volume of tenant requests.',
    phone: '(717) 819-9339',
    email: 'TMeinl@Statewide-PM.com',
    painPoint: 'Filtering non-emergency tenant complaints from actual crises and routing third-party contractors.',
    pitchTitle: 'Maintenance Request AI Filter',
    pitchText: 'I build automation systems for logistics. I can build you an AI agent that takes maintenance emails/texts from tenants, figures out if it is an emergency, logs it in your system, and automatically requests quotes from your approved contractor list.',
    status: 'Follow Up',
    colorHint: 'purple',
    yearsOperational: '10+ Years',
    currentStandings: 'Manages 500+ Units',
    businessReview: 'Growing portfolio but drowning in low-level tenant communications and maintenance coordination.'
  },
  {
    id: '4',
    companyName: "Mark's Paving & Blacktop",
    category: 'Logistics / Paving',
    location: 'Hershey, PA',
    description: 'Regional paving with specific zones (Hershey, Camp Hill, Lancaster).',
    phone: '(717) 533-4870',
    email: 'email@email.com',
    painPoint: 'Tracking multi-region heavy equipment deployment and managing weather-delayed schedule shifts.',
    pitchTitle: 'Multi-Region Route & Equipment Tracker',
    pitchText: 'With teams split between Hershey and Lancaster, manual scheduling is a bottleneck. I manage multi-state physical assets professionally. I can build you an automated dashboard that reorganizes your paving routes instantly when weather delays hit.',
    status: 'New Lead',
    colorHint: 'orange',
    yearsOperational: '20+ Years',
    currentStandings: 'A+ BBB Rating',
    businessReview: 'Highly respected family business. Great work quality, but operational scaling is capped by manual oversight.'
  },
  {
    id: '5',
    companyName: 'W.C. Eshenaur & Son',
    category: 'Logistics / Fuel',
    location: 'Hummelstown, PA',
    description: 'Dual services: Propane delivery routes AND HVAC repair dispatch.',
    phone: '(717) 236-5031',
    email: 'Via Website Form',
    painPoint: 'Two separate logical routing needs: recurring fuel delivery loops vs. spontaneous HVAC breakdown calls.',
    pitchTitle: 'Dual-Logic Logistics Automation',
    pitchText: 'Managing fixed propane routes while fielding random HVAC emergencies is tough. I build operational systems. I can deploy an automated framework that alerts customers of their delivery window via SMS, reducing office call volume by 40%.',
    status: 'New Lead',
    colorHint: 'green',
    yearsOperational: 'Est. 1928',
    currentStandings: '4.8/5 Stars (Google)',
    businessReview: 'Deeply entrenched local business with complex, multi-faceted service lines that desperately need unified digital tracking.'
  },
  {
    id: '6',
    companyName: 'Chop Chop Landscaping',
    category: 'Network / Contractors',
    location: 'Harrisburg, PA',
    description: 'Functions as a network connecting homeowners to third-party landscaping contractors.',
    phone: '(717) 687-2323',
    email: 'Via Website Form',
    painPoint: 'Matching the right contractor capability (hardscaping vs lawn care) with the homeowner\'s request quickly.',
    pitchTitle: 'Automated Lead Matching System',
    pitchText: 'Connecting leads to the right third-party contractor is a pure data routing problem. I build multi-agent systems. I can create an automated workflow that reads a homeowner request, matches it to the right contractor by zip code, and texts the contractor instantly.',
    status: 'New Lead',
    colorHint: 'yellow',
    yearsOperational: '5+ Years',
    currentStandings: 'Fast Growing',
    businessReview: 'Modern business model acting as a middleman. High potential for AI integration to fully automate their core value proposition.'
  }
];

export const STATUS_COLORS: Record<LeadStatus, string> = {
  'New Lead': 'bg-slate-700 text-slate-300',
  'Contacted': 'bg-blue-900/50 text-blue-300 border-blue-700',
  'Follow Up': 'bg-yellow-900/50 text-yellow-300 border-yellow-700',
  'Meeting Set': 'bg-purple-900/50 text-purple-300 border-purple-700',
  'Proposal Sent': 'bg-indigo-900/50 text-indigo-300 border-indigo-700',
  'Closed Won': 'bg-green-900/50 text-green-300 border-green-700',
  'Closed Lost': 'bg-red-900/50 text-red-300 border-red-700',
};
